# IMPORTANT: see local.yaml in this same directory for why this must stay outside apps/, and for
# why this uses v1, not v1beta1.
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-irsa
            namespace: external-secrets
